on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/SAST.yml
name: Semgrep vs SonarQube
jobs:
  semgrep-free:
    name: semgrep-free
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: |
        semgrep scan --json --json-output /tmp/semgrep.json
    - name: View the output
      run: cat /tmp/semgrep.json
  semgrep-pro:
    name: semgrep-pro
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: |
        semgrep ci --json --json-output /tmp/semgrep.json
    - name: View the output
      run: cat /tmp/semgrep.json